version: '3'

silent: false

tasks:
  default:
    cmds:
      - task: switch

  switch:
    desc: Switch environment
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: nix run .#system_manager -- switch --flake .#main_wsl --sudo
        platforms: [linux/amd64]
      - cmd: sudo darwin-rebuild switch --flake .
        platforms: [darwin/arm64]

  update:
    desc: Update pkgs
    cmds:
      - cmd: nix flake update
      - cmd: brew update
        platforms: [darwin/arm64]
      - cmd: echo "Update complete, run 'task' to switch"

  gc:
    desc: Clean Nix profiles and store older than 30 days
    cmds:
      - cmd: nh clean all --keep-since 30d --keep-one

  check:
    desc: Run all check
    cmd: nix flake check --all-systems

  fmt:
    desc: Format nix files
    cmds:
      - cmd: nix fmt

  winget:build:
    desc: Build WinGet configuration
    dir: config/winget
    cmd: nickel export --format yaml --output output/configuration.winget main.ncl

  winget:validate:
    desc: Validate WinGet configuration
    dir: config/winget
    cmd: winget.exe configure validate --file "$(wslpath -w output/configuration.winget)"

  winget:fmt:
    desc: Format WinGet Nickel files
    dir: config/winget
    cmd: find . -type f -name '*.ncl' -exec nickel format {} +

  winget:apply:
    desc: Apply WinGet configuration on Windows host
    dir: config/winget
    cmd: winget.exe configure --file "$(wslpath -w output/configuration.winget)"

  winget:test:
    desc: Test WinGet configuration on Windows host
    dir: config/winget
    cmd: bash util/test.sh

  first_switch:
    desc: First time setup for home-manager and nix-darwin (only macOS)
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: nix run .#system_manager -- switch --flake . --sudo
        platforms: [linux/amd64]
      - cmd: sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake .
        platforms: [darwin/arm64]
