version: '3'

silent: false

tasks:
  default:
    cmds:
      - task: switch

  switch:
    desc: Switch environment via home-manager and nix-darwin (only macOS)
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: home-manager switch
        platforms: [linux/amd64]
      - cmd: sudo darwin-rebuild switch
        platforms: [darwin/arm64]

  first_switch:
    desc: First time setup for home-manager and nix-darwin (only macOS)
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: nix run home-manager/master --switch
        platforms: [linux/amd64]
      - cmd: sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake .
        platforms: [darwin/arm64]
