version: '3'

silent: false

tasks:
  default:
    cmds:
      - task: switch

  switch:
    desc: Switch environment via home-manager and nix-darwin (only macOS)
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: home-manager switch --flake .
        platforms: [linux/amd64]
      - cmd: sudo darwin-rebuild switch --flake .
        platforms: [darwin/arm64]

  update:
    desc: Update pkgs
    cmds:
      - cmd: nix flake update
      - cmd: brew update
        platforms: [darwin/arm64]
      - cmd: echo "Update complete, run 'task' to switch"

  gc:
    desc: Clean Nix profiles and store older than 30 days
    cmds:
      - cmd: nh clean all --keep-since 30d --keep-one

  check:
    desc: Run all check
    cmd: nix flake check --all-systems

  fmt:
    desc: Format nix files
    cmds:
      - cmd: nix fmt

  first:
    desc: First time setup for System Manager (only WSL)
    platforms: [linux/amd64]
    cmds:
      - cmd: nix run 'github:numtide/system-manager' -- switch --flake . --sudo

  system:
    desc: Switch environment via System Manager (only WSL)
    platforms: [linux/amd64]
    cmds:
      - cmd: nix run .#system_manager -- switch --flake . --sudo

  first_switch:
    desc: First time setup for home-manager and nix-darwin (only macOS)
    platforms: [linux/amd64, darwin/arm64]
    cmds:
      - cmd: nix run home-manager/master -- switch --flake .
        platforms: [linux/amd64]
      - cmd: sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake .
        platforms: [darwin/arm64]
